// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
.........................
.........................
..ffff....f.....f........
..ffff....bf454fb........
....55ff...fb4bf.........
....55ff..881b188........
....ff55..55fbf55........
....ff55.588fbf885.......
....ff...4548f8554.......
....ff...f54858544.......
..ffff545588848885f......
..ffffff455554555ff......
..ffffffff.fffff..45.....
....ff.....4fff4..ff.....
....ff....4555544..f.....
....ff....4555544.ff.....
....ff....5555555.ff.....
..ff..ff.455555f5.ff.....
..ff..ff.5fff..f.........
..ff..ff....f..ff........
`;
            case "image3":
            case "myImage1":return img`
.........................
.........................
...ff..............ff....
..fccff...........fccf...
..fccccf.........fcccf...
...fccccfffffffffccccf...
....fccffcccccccffccff...
.....fffc1fcccf1cfff.....
......fcc11ccc11ccfffff..
.....ffcccccccccccf666f..
....f.fccfcccccfccf998ff.
....f..fccfcccfccf66666f.
...f.f..f4fcccf4f66899ff.
..f..ffff64fcf46fff998f..
.....fddf86fbf68fddf66f..
.....fddf588f885fddffff..
.....ffffd55555dfcc......
.....f..fdddddddfc.c.....
.....f..f4444444f.c.c....
.....f..f1114444fccc.....
.....f..f111f444f.c......
......fff11f.f44ffc......
.....fddddf...fddddf.....
......ffff.....ffff......
.........................
`;
            case "image1":
            case "myImage":return img`
....................
....................
.......fffffff......
......ffeeeeeff.....
.....feeeeeeeeef....
.....feeffdffddf....
.....feddddddddf....
.....fddddfddddf....
......f1dd1d1df.....
....fff1111111fff...
...fddfe11ee11fddf..
...fddfeeeeeeefddf..
....fffeeeeeeefff...
......feeeeeeef.....
......f7eeee77f.....
......f7777777f.....
......f777f777f.....
.....ff7df.f7dff....
....fdddf...fdddf...
.....fff.....fff....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
